version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 4000:4000 # debugging service (ptvsd)
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG}
      - DB_HOST=db

    depends_on:
      - db
    # command: >
    #   sh -c "./wait-for-it.sh db:5432 -- python manage.py makemigrations &&
    #          python manage.py migrate &&
    #          python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
