# Generated by Django 4.0 on 2023-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mediaItems', '0004_auto_20230726_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
