# Generated by Django 4.0 on 2023-08-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiontask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptiontask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=10),
        ),
    ]
