# Generated by Django 4.0 on 2023-07-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_on',
            new_name='updated',
        ),
    ]
