# Generated by Django 4.0 on 2023-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mediaItems', '0002_alter_mediaitem_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
