# Generated by Django 4.0 on 2023-07-26 03:50

from django.db import migrations, models
import json

def convert_url_to_jsonfield(apps, schema_editor):
    MediaItem = apps.get_model('core_mediaItems', 'MediaItem')

    # Convert 'url' values from CharField to JSONField format
    for item in MediaItem.objects.all():
        item.url = None
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core_mediaItems', '0003_alter_mediaitem_type_alter_mediaitem_url'),
    ]

    operations = [
        migrations.RunPython(convert_url_to_jsonfield),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.JSONField(default=None, null=True),
        ),
    ]