# Generated by Django 4.0 on 2023-08-23 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_mediaItems', '0006_mediaitem_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMediaItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200)),
                ('output', models.JSONField()),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_mediaItems.mediaitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
