# Generated by Django 4.0 on 2023-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mediaItems', '0007_processedmediaitemresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedmediaitemresult',
            name='output',
            field=models.JSONField(default={}),
        ),
    ]
